### ISSUE TITLE
source image text prompt

### ISSUE THREAD

**Issue by Harperrrr111** [eric-ai-lab/photoswap#2]
Nice work!

I have a simple question after reading the paper. If we use a real image as the source image, how can we set its text prompt?

**Comment by g-jing** [comment]
Thanks for your interest in our work. The caption can be manually designed or generated by a captioning model. We found both methods effective.

**Comment by Harperrrr111** [comment]
@g-jing   Got it!  Btw, waiting for your release of the code~

**Comment by g-jing** [comment]
The code is released now. Please let me know if there is any issue.
