### ISSUE TITLE
Support diffusers > v0.14

### ISSUE THREAD

**Issue by hoveychen** [eric-ai-lab/photoswap#7]
Per https://github.com/eric-ai-lab/photoswap/issues/6, the current code does not work for the current version of diffusers. 
That would block us from testing the technique in a wider range of dataset.

The latest version of diffusers supports loading LoRA weights into the base model. In our repository, most the of concept injected models, either downloaded from Civitai, or finetuned with DreamBooth, are saved in LoRA models.

**Comment by g-jing** [comment]
Thanks for your suggestions. We will update the diffusers recently.
